version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm update
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
